### ISSUE TITLE
setup documentation

### ISSUE THREAD

**Issue by unnir** [ucb-art/BAG_framework#1]
Hi all, 

thank you for the repo. 

Just one question:
How can I configure the BAG framework for my Cadence Virtuoso? I could not find it in the documentation. 

kind regards, 
Vadim

**Comment by unnir** [comment]
I think a have more than one question :smiley: 

In the docs, in order to start I have to clone a repo from berkley git:

```
> git clone git@bwrcrepo.eecs.berkeley.edu:BAG/BAG2_TSMC65_tutorial.git
> mv BAG2-TSMC65GP-WORKSPACE bag_tutorial
> cd bag_tutorial
```
The problem is I don't have an access, is there a way to get this data? I know about NDA stuff, but perhaps you can share setups for gpdk045/090 or for freePDK. 

-
Vadim

**Comment by redpanda3** [comment]
Maybe you can config a new model file.

**Comment by pkerichang** [comment]
Hello,

due to NDA we cannot share the setup for any real processes.  Please check out https://github.com/ucb-art/BAG2_cds_ff_mpt.git for the process independent tutorial.
