### ISSUE TITLE
possilbe to split server and client?

### ISSUE THREAD

**Issue by sequencer** [ucb-art/BAG_framework#20]
I'm using Arch Linux for client, while a CentOS core 7.5 as virtuoso server.
I wonder if it possible to run a minimal BAG server on server, while using a whole bag_framework on my Arch Linux.

**Comment by pkerichang** [comment]
This won't be officially supported, as many operations (LVS, PEX, simulations) are run on the client machine, so unless you got the whole CAD environment installed on your client these operations won't run.

However, if you just want to talk with virtuoso, you can setup port forwarding between server and client.  To do, first start the BAG server on virtuoso, then find the port number in BAG_server_port.txt, then forward that port to your client machine.

**Comment by sequencer** [comment]
Oh I got it, thank you. So if I need to do so, I must wrapper whole LVS, PEX, and simulations?
That sound a little hard, I'm going to try it.

**Comment by pkerichang** [comment]
Closing this issue for now.

By the way, as a word of caution,  it is generally against foundry NDA to have technology specific files (PDKs, data files containing technology specific parameters, etc.) on a client machine, which is why BAG is not built with that support.  If you do decide to have a separate server/client please review the NDA carefully and make sure you are not violating their terms and conditions.

**Comment by sequencer** [comment]
oh, I got it.
You are right. NDA is the main problem.
Maybe I should package a whole lsb runtime for EDA tools for Arch Linux, which has a modern python environment. :P

**Comment by pkerichang** [comment]
The way I solve this problem is by installing my own development tools on a network drive, then setup my .bashrc to point to that instead.  You can use Anaconda Python if you are unfamiliar with how to compile various C extension libraries.

**Comment by sequencer** [comment]
I got it, I have already running a correct environment with `python3.6` and `pip` on `CentOS Core 7.5` nsapwn from `Arch Linux`.(which is my EDA server), that works fine.
However the problem is that the quality of python packages is not so good as Arch Linux.
And `tornado` bug has fixed in `python 3.7`, however `CentOS` might package `python3.7` maybe 1 year later, that's the main problem with CentOS. :(
