### ISSUE TITLE
Module openmdao.api has no attribute 'Component'

### ISSUE THREAD

**Issue by lduncantdkc** [ucb-art/BAG_framework#23]
I am receiving the following error when running the following script from laygo:
laygo/generators/adc_sar/adc_sar_sarsamp_size.py

```
BAG_framework/bag/mdao/components.py in <module>()
      8 
      9 
---> 10 class VecFunComponent(omdao.Component):
     11     """A component based on a list of functions.
     12 

AttributeError: module 'openmdao.api' has no attribute 'Component'
```

**Comment by lduncantdkc** [comment]
It appears that openmdao.api.Component was removed in OpenMDAO 2.2.0. Downgrading to 2.1.0 solved the problem for now:

`pip install openmdao==2.1.0`

**Comment by pkerichang** [comment]
Thanks for the heads up.
