### ISSUE TITLE
BAG versioning guideline?

### ISSUE THREAD

**Issue by mkosunen** [ucb-art/BAG_framework#28]
Hi @pkerichang, (ping @low-pass)
I have couple of newbie questions, ans I ask them here as they may benefit other user willing to get into the wonderful world of BAG.

This is the first one: Which branches are:
1) The development branch of the BAG
2) Latest stable release.

I.e which repositories and modules to clone.

It would be nice to have them documented in the README with some suggestions for the newbies which branch to use and how. I can write those as soon as I have the information.
Thanks,
Marko

**Comment by pkerichang** [comment]
The master branch is the lastest stable release for now, and all other branches are considered development branches.

After BAG 3.0 is officially released, the current master branch will be moved to "bag2" branch and basically stay in maintenance mode for people who haven't/choose not to migrate to BAG 3.0
