### ISSUE TITLE
Minimum working example

### ISSUE THREAD

**Issue by mkosunen** [ucb-art/BAG_framework#29]
Hi @pkerichang,
This is the second question related to #28 . 

A minimum working example containing a transistor, a resistor and a capacitor could serve well as a starting point for any BAG design. If this exists already, it should be mentioned in the README of the latest stable release. 

If it doesn't. I or ( @low-pass ) can create it once #28 is solved.
Thanks,
Marko

**Comment by pkerichang** [comment]
Right now the tutorial repo (BAG2_cds_ff_mpt, mentioned in the README) serves as the working example repository.  Open source generator repos I maintain (bag_digital_ec, bag_analog_ec, etc.) will have examples/tests working with the cds_ff_mpt technology.
