### ISSUE TITLE
BAG3: Module.remove_instance and Module.delete_instance functionality not equivalent

### ISSUE THREAD

**Issue by aviralpandey** [ucb-art/BAG_framework#38]
In the module class, calling `delete_instance` does not actually remove the instance as `remove_instance` does. The suspect lines of code are below, from `BagFramework/src/design/module.py`

```python
def delete_instance(self, inst_name):
   return self._cv.remove_instance(inst_name)
```

```python 
def remove_instance(self, inst_name):
    success = self._cv.remove_instance(inst_name)
    if success:
        del self.instances[inst_name]
    return success
```

Most legacy code contains calls to `delete_instance` not `remove_instance`.

**Comment by pkerichang** [comment]
Thanks for the catch.  During development there was a reason why there should be two different methods, but that has changed now.  I removed the remove_instance() method and kept delete_instance in the laster master.
