### ISSUE TITLE
no resposne bag server

### ISSUE THREAD

**Issue by gdutee** [ucb-art/BAG_framework#5]
It seems when try to import schematic no response from bag server
I have load("start-bag.il”) and run virtual_server.s.h

In [25]: bprj.import_design_library('demo_templates')
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-25-e9ca2952319d> in <module>()
----> 1 bprj.import_design_library('demo_templates')

/bagf/BAG2_csoi7rf/BAG_framework/bag/core.py in import_design_library(self, lib_name)
    549 
    550         new_lib_path = self.bag_config['new_lib_path']
--> 551         self.impl_db.import_design_library(lib_name, self.dsn_db, new_lib_path)
    552 
    553     def get_cells_in_library(self, lib_name):

/proj/bagf/BAG2_csoi7rf/BAG_framework/bag/interface/database.py in import_design_library(self, lib_name, dsn_db, new_lib_path)
    533         """
    534         imported_cells = set()
--> 535         for cell_name in self.get_cells_in_library(lib_name):
    536             self._import_design(lib_name, cell_name, imported_cells, dsn_db, new_lib_path)
    537 

/bagf/BAG2_csoi7rf/BAG_framework/bag/interface/skill.py in get_cells_in_library(self, lib_name)
    213         """
    214         cmd = 'get_cells_in_library_file( "%s" {cell_file} )' % lib_name
--> 215         return self._eval_skill(cmd, out_file='cell_file').split()
    216 
    217     def create_library(self, lib_name, lib_path=''):

/bagf/BAG2_csoi7rf/BAG_framework/bag/interface/skill.py in _eval_skill(self, expr, input_files, out_file)
    176 
    177         self.handler.send_obj(request)
--> 178         reply = self.handler.recv_obj()
    179         return _handle_reply(reply)
    180 

/bagf/BAG2_csoi7rf/BAG_framework/bag/interface/zmqwrapper.py in recv_obj(self, timeout, enable_cancel)
    100         """
    101         try:
--> 102             events = self.poller.poll(timeout=timeout)
    103         except KeyboardInterrupt:
    104             if not enable_cancel:

/home/jjww/anaconda3/lib/python3.6/site-packages/zmq/sugar/poll.py in poll(self, timeout)
     97         elif isinstance(timeout, float):
     98             timeout = int(timeout)
---> 99         return zmq_poll(self.sockets, timeout=timeout)
    100 
    101 

zmq/backend/cython/_poll.pyx in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2036)()

/home/jjww/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/checkrc.pxd in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:2418)()

**Comment by gdutee** [comment]
Is any way to debug the issue? thank you

**Comment by gdutee** [comment]
here is the skill_server.log

received data:
{'expr': 'get_cells_in_library_file( "demo_templates" {cell_file} )',
 'input_files': None,
 'out_file': 'cell_file',
 'type': 'skill'}
~

**Comment by gdutee** [comment]
also socket log seems send data

sending data:
{'expr': 'get_cells_in_library_file( "demo_templates" {cell_file} )',
 'input_files': None,
 'out_file': 'cell_file',
 'type': 'skill'}
sending data:
{'expr': 'get_cells_in_library_file( "demo_templates" {cell_file} )',
 'input_files': None,
 'out_file': 'cell_file',
 'type': 'skill'}

**Comment by gdutee** [comment]
I add timeout in zmqwrapper, seems the problem is no data being received 

    def recv_obj(self, timeout=30000, enable_cancel=False):

**Comment by gdutee** [comment]
sending data:
{'expr': 'get_cells_in_library_file( "demo_templates" {cell_file} )',
 'input_files': None,
 'out_file': 'cell_file',
 'type': 'skill'}

timeout with 30000 ms reached.

**Comment by pkerichang** [comment]
Did you run BAG and Virtuoso on the same machine?  BAG and Virtuoso communicates through local ports.

**Comment by pkerichang** [comment]
Closed for no response.  However, for tutorial please visit:

https://github.com/ucb-art/BAG2_cds_ff_mpt.git
