### ISSUE TITLE
Error in tech.py 

### ISSUE THREAD

**Issue by prjwlk** [ucb-art/BAG_framework#51]
Under cds_ff_mpt/templates_cds_ff_mpt/tech.py:
    
 16         TechInfoConfig.__init__(self, _config, process_params)
     17 
---> 18         process_params['layout']['mos_tech_class'] = MOSTechCDSFFMPT(_config, self)
     19         process_params['layout']['laygo_tech_class'] = None
     20         process_params['layout']['res_tech_class'] = None

TypeError: Can't instantiate abstract class MOSTechCDSFFMPT with abstract methods is_planar_substrate

**Comment by pvnbhargava** [comment]
It looks like you are using an old version of cds_ff_mpt and a new version of BAG_framework. What commit is cds_ff_mpt currently pointing to in your setup? We will be opening up the cds_ff_mpt repo again soon. When that goes live, please pull the latest updated version. In the mean time to circumvent this issue, you may want to add this to your MOSTechCDSFFMPT class:
```python
    def is_planar_substrate(self, lch_unit, **kwargs):
        # return True to draw planar style substrate
        return False
```
There may be other abstract methods you are missing, so giving me your commit number will allow me to help you better.

**Comment by sbuchbinder** [comment]
We have just made cds_ff_mpt public again.

You will need to perform the following (git history has been modified):
```
cd cds_ff_mpt
git fetch --all
git reset --hard origin/master
```

Let us know if there are any issues.

**Comment by prjwlk** [comment]
Hi,

Thanks for the BAG2_cds_ff_mpt upload. I am able to get past the first stage now but now I see this:
skill.py in _handle_reply(reply)
     78             if 'data' not in reply:
     79                 raise Exception('Unknown reply format: %s' % reply)
---> 80             raise VirtuosoException(reply['data'])
     81         else:
     82             try:

VirtuosoException: *Error* Via technology file cds_ff_mpt not found.

**Comment by prjwlk** [comment]
Hi,
Thanks for the latest upload on BAG2_cds_ff_mpt. 
My run flow now stops on the tb.simulate command:
python3.7/asyncio/base_events.py in run_forever(self)
    524         self._check_closed()
    525         if self.is_running():
--> 526             raise RuntimeError('This event loop is already running')
    527         if events._get_running_loop() is not None:
    528             raise RuntimeError(

RuntimeError: This event loop is already running

Any ideas what this might be?
Thanks
